### PR TITLE
Small clean up to align with dgramop/parameters

### PR DESCRIPTION
**Pull request by ruevs**
@dgramop I think that it is better to merge your dgramop/parameters_messy branch instead of dgramop/parameters into the upstream parameters branch in order to retain the history of how it happened.

When it is ready to merge into master I will do an interactive rebase and keep some subset of "meaningful" commits.

To that end I am submitting this pull request to make dgramop/parameters_messy exactly the same as dgramop/parameters.

### CODE REVIEW

**Review by dgramop — APPROVED** [review]
parameters_messy's git history is my dirty laundry, but if you want it it's yours haha.

**Comment by dgramop** [comment]
Should I submit a PR from dgramop:parameters_messy -> solvespace:parameters and close my dgramop:parameters -> solvespace:parameters?

**Comment by ruevs** [comment]
Yes please. By the way it works pretty well - I played with it a bit yesterday.

Edit - we avoid merge commits in SolveSpace - instead we exclusively use rebasing. If you want I can make the PR from my branch?

**Comment by dgramop** [comment]
I just bumped off the PR merge commit to flatten history, when diffed with post-merge commit there were no changes, and it got all 3 of your commits. Thanks for those changes by the way! I definitely spent a few minutes making silly arbitrary constraints after I got things working. 

I'll go ahead and (edit: update the old PR)

**Comment by dgramop** [comment]
I bumped off my old squash commit (now tagged "squashed_version") and rebased parameters_messy onto parameters so we can keep using the original PR

**Pull request merged**
